
"""
GeoMaka POS Add Expense Window

File:
gui/expense_add_window.py

Purpose:
Provide the GUI for adding a new expense.

Responsibilities:

- Display the Add Expense window.
- Accept expense name.
- Accept expense description.
- Accept expense cost amount.
- Validate entered information.
- Save the expense through the expense management module.
- Show success/error messages.
- Restore the parent window when closed.

Important:

- Expense ID is generated by the database.
- Expense date is generated by the backend.
- Created At is generated by the backend.
- Entered By is obtained from the logged-in session.
- Cashier access must be prevented by the calling module/dashboard.

Company:
GeoMaka Technologies
"""

import tkinter as tk
from tkinter import messagebox


# ==========================================================
# EXPENSE MANAGEMENT
# ==========================================================

from modules.expenses.expense_management import (
    add_expense
)


# ==========================================================
# CENTER WINDOW
# ==========================================================

def center_window(
    window,
    width,
    height
):
    """
    Centers a Tkinter window on the screen.
    """

    screen_width = (
        window.winfo_screenwidth()
    )

    screen_height = (
        window.winfo_screenheight()
    )

    x = (
        screen_width // 2
        -
        width // 2
    )

    y = (
        screen_height // 2
        -
        height // 2
    )

    window.geometry(
        f"{width}x{height}+{x}+{y}"
    )


# ==========================================================
# ADD EXPENSE WINDOW
# ==========================================================

def open_expense_add_window(
    parent,
    on_saved=None
):
    """
    Opens the Add Expense window.

    Parameters:

        parent:
            Parent Tkinter window.

        on_saved:
            Optional callback executed after an expense
            has been successfully saved.

    Returns:

        Tkinter Toplevel window.
    """

    # ======================================================
    # HIDE PARENT
    # ======================================================

    if (
        parent
        and
        parent.winfo_exists()
    ):

        parent.withdraw()


    # ======================================================
    # CREATE WINDOW
    # ======================================================

    root = tk.Toplevel(
        parent
    )

    root.title(
        "ADD EXPENSE"
    )

    root.resizable(
        False,
        False
    )

    center_window(
        root,
        500,
        430
    )


    # ======================================================
    # CLOSE WINDOW
    # ======================================================

    def close_window():

        root.destroy()

        if (
            parent
            and
            parent.winfo_exists()
        ):

            parent.deiconify()


    # ======================================================
    # TITLE
    # ======================================================

    tk.Label(
        root,
        text="ADD EXPENSE",
        font=(
            "Arial",
            16,
            "bold"
        )
    ).pack(
        pady=15
    )


    # ======================================================
    # FORM FRAME
    # ======================================================

    form_frame = tk.Frame(
        root
    )

    form_frame.pack(
        padx=30,
        pady=5,
        fill="x"
    )


    # ======================================================
    # EXPENSE NAME
    # ======================================================

    tk.Label(
        form_frame,
        text="Expense Name:"
    ).grid(
        row=0,
        column=0,
        sticky="w",
        pady=8
    )


    expense_name_entry = tk.Entry(
        form_frame,
        width=40
    )

    expense_name_entry.grid(
        row=0,
        column=1,
        padx=10,
        pady=8
    )


    # ======================================================
    # DESCRIPTION
    # ======================================================

    tk.Label(
        form_frame,
        text="Description:"
    ).grid(
        row=1,
        column=0,
        sticky="nw",
        pady=8
    )


    description_text = tk.Text(
        form_frame,
        width=30,
        height=5,
        wrap="word"
    )

    description_text.grid(
        row=1,
        column=1,
        padx=10,
        pady=8
    )


    # ======================================================
    # COST AMOUNT
    # ======================================================

    tk.Label(
        form_frame,
        text="Cost Amount (M):"
    ).grid(
        row=2,
        column=0,
        sticky="w",
        pady=8
    )


    cost_amount_entry = tk.Entry(
        form_frame,
        width=40
    )

    cost_amount_entry.grid(
        row=2,
        column=1,
        padx=10,
        pady=8
    )


    # ======================================================
    # SAVE EXPENSE
    # ======================================================

    def save_expense():

        # --------------------------------------------------
        # GET VALUES
        # --------------------------------------------------

        expense_name = (
            expense_name_entry
            .get()
            .strip()
        )


        description = (
            description_text
            .get(
                "1.0",
                "end"
            )
            .strip()
        )


        cost_amount_text = (
            cost_amount_entry
            .get()
            .strip()
        )


        # --------------------------------------------------
        # VALIDATE EXPENSE NAME
        # --------------------------------------------------

        if not expense_name:

            messagebox.showwarning(
                "Validation Error",
                "Please enter the expense name.",
                parent=root
            )

            expense_name_entry.focus_set()

            return


        # --------------------------------------------------
        # VALIDATE DESCRIPTION
        # --------------------------------------------------

        if not description:

            messagebox.showwarning(
                "Validation Error",
                "Please enter the expense description.",
                parent=root
            )

            description_text.focus_set()

            return


        # --------------------------------------------------
        # VALIDATE COST AMOUNT
        # --------------------------------------------------

        if not cost_amount_text:

            messagebox.showwarning(
                "Validation Error",
                "Please enter the expense cost amount.",
                parent=root
            )

            cost_amount_entry.focus_set()

            return


        # --------------------------------------------------
        # CONVERT COST TO NUMBER
        # --------------------------------------------------

        try:

            cost_amount = float(
                cost_amount_text
            )


        except ValueError:

            messagebox.showwarning(
                "Validation Error",
                "Cost amount must be a valid number.",
                parent=root
            )

            cost_amount_entry.focus_set()

            return


        # --------------------------------------------------
        # PREVENT ZERO/NEGATIVE EXPENSES
        # --------------------------------------------------

        if cost_amount <= 0:

            messagebox.showwarning(
                "Validation Error",
                "Cost amount must be greater than zero.",
                parent=root
            )

            cost_amount_entry.focus_set()

            return


        # --------------------------------------------------
        # SAVE EXPENSE
        # --------------------------------------------------

        try:

            result = add_expense(
                expense_name,
                description,
                cost_amount
            )


        except Exception as error:

            messagebox.showerror(
                "Add Expense Error",
                (
                    "The expense could not be added.\n\n"
                    f"Error:\n{error}"
                ),
                parent=root
            )

            return


        # --------------------------------------------------
        # HANDLE FAILED SAVE
        # --------------------------------------------------

        if result is False:

            messagebox.showerror(
                "Add Expense Error",
                "The expense could not be added.",
                parent=root
            )

            return


        # --------------------------------------------------
        # SUCCESS MESSAGE
        # --------------------------------------------------

        messagebox.showinfo(
            "Expense Added",
            "Expense added successfully.",
            parent=root
        )


        # --------------------------------------------------
        # REFRESH PARENT WINDOW
        # --------------------------------------------------

        if callable(
            on_saved
        ):

            try:

                on_saved()

            except Exception:

                pass


        # --------------------------------------------------
        # CLOSE WINDOW
        # --------------------------------------------------

        close_window()


    # ======================================================
    # BUTTON FRAME
    # ======================================================

    button_frame = tk.Frame(
        root
    )

    button_frame.pack(
        pady=20
    )


    # ======================================================
    # SAVE BUTTON
    # ======================================================

    tk.Button(
        button_frame,
        text="Save",
        width=14,
        bg="#27ae60",
        fg="white",
        command=save_expense
    ).pack(
        side="left",
        padx=5
    )


    # ======================================================
    # CANCEL BUTTON
    # ======================================================

    tk.Button(
        button_frame,
        text="Cancel",
        width=14,
        bg="#7f8c8d",
        fg="white",
        command=close_window
    ).pack(
        side="left",
        padx=5
    )


    # ======================================================
    # WINDOW CLOSE EVENT
    # ======================================================

    root.protocol(
        "WM_DELETE_WINDOW",
        close_window
    )


    # ======================================================
    # INITIAL FOCUS
    # ======================================================

    expense_name_entry.focus_set()


    return root

