
from modules.system.app_paths import get_audit_directory

# ==========================================================
# SAVE TEXT FILE
# ==========================================================

def _save_text_file(filename, content):

    audit_directory = get_audit_directory()


    audit_directory.mkdir(
        parents=True,
        exist_ok=True
    )


    file_path = (
        audit_directory
        /
        filename
    )


    with open(
        file_path,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(content)



    return file_path





# ==========================================================
# AUDIT TABLE FORMATTER
# ==========================================================

def _format_audit_table(logs):


    text = ""


    text += (
        "-" * 130
        +
        "\n"
    )


    text += (
        f"{'Date & Time':20}"
        f"{'Username':15}"
        f"{'Role':15}"
        f"{'Module':15}"
        f"{'Action':15}"
        f"{'Description':40}\n"
    )


    text += (
        "-" * 130
        +
        "\n"
    )



    for log in logs:


        text += (

            f"{str(log['log_datetime']):20}"

            f"{str(log['username']):15}"

            f"{str(log['role']):15}"

            f"{str(log['module']):15}"

            f"{str(log['action']):15}"

            f"{str(log['description']):40}"

            "\n"

        )



    text += (
        "-" * 130
        +
        "\n"
    )


    return text





# ==========================================================
# SAVE AUDIT LOG REPORT
# ==========================================================

def save_audit_logs_report(
        generated,
        logs
):


    content = ""



    content += (
        "=" * 130
        +
        "\n"
    )


    content += (
        " " * 50
        +
        "AUDIT LOG REPORT\n"
    )


    content += (
        "=" * 130
        +
        "\n\n"
    )



    content += (
        f"Generated : {generated}\n\n"
    )



    content += _format_audit_table(logs)



    content += "\n"



    content += (
        "=" * 130
        +
        "\n"
    )


    content += (
        "Generated by POS System\n"
    )


    content += (
        "=" * 130
    )



    filename = (
        "audit_logs.txt"
    )



    return _save_text_file(
        filename,
        content
    )