from datetime import datetime

from modules.system.app_paths import get_reports_directory


# ==========================================================
# SAVE TEXT FILE
# ==========================================================

def _save_text_file(filename, content):

    reports_directory = get_reports_directory()

    reports_directory.mkdir(
        parents=True,
        exist_ok=True
    )

    file_path = reports_directory / filename

    with open(
        file_path,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(content)


    return file_path



# ==========================================================
# SALES TABLE FORMATTER
# ==========================================================

def _format_sales_table(rows):

    text = ""

    text += (
        "-" * 150
        + "\n"
    )

    text += (
        f"{'Product':25}"
        f"{'Barcode':15}"
        f"{'Unit Cost(M)':15}"
        f"{'Unit Price(M)':15}"
        f"{'Quantity':10}"
        f"{'Total Cost(M)':15}"
        f"{'Gross Sales(M)':15}"
        f"{'Discount(M)':15}"
        f"{'Net Sales(M)':15}"
        f"{'Profit/Loss(M)':15}\n"
    )


    text += (
        "-" * 150
        + "\n"
    )


    for row in rows:

        text += (
            f"{str(row[0]):25}"
            f"{str(row[1]):15}"
            f"{row[2]:15.2f}"
            f"{row[3]:15.2f}"
            f"{row[4]:10}"
            f"{row[5]:15.2f}"
            f"{row[6]:15.2f}"
            f"{row[7]:15.2f}"
            f"{row[8]:15.2f}"
            f"{row[9]:15.2f}\n"
        )


    text += (
        "-" * 150
        + "\n"
    )


    return text



# ==========================================================
# STOCK TABLE FORMATTER
# ==========================================================

def _format_stock_table(rows):

    text = ""

    text += (
        "-" * 70
        + "\n"
    )


    text += (
        f"{'Product':35}"
        f"{'Opening Stock':15}"
        f"{'Quantity Sold':15}"
        f"{'Closing Stock':15}\n"
    )


    text += (
        "-" * 70
        + "\n"
    )


    total_open = 0
    total_sold = 0
    total_close = 0


    for row in rows:

        product, sold, closing, opening = row


        text += (
            f"{product:35}"
            f"{opening:<15}"
            f"{sold:<15}"
            f"{closing:<15}\n"
        )


        total_open += opening
        total_sold += sold
        total_close += closing



    text += (
        "-" * 70
        + "\n"
    )


    text += (
        f"{'TOTAL':35}"
        f"{total_open:<15}"
        f"{total_sold:<15}"
        f"{total_close:<15}\n"
    )


    text += (
        "-" * 70
        + "\n"
    )


    return text



# ==========================================================
# DAILY SALES REPORT EXPORT
# ==========================================================

def save_daily_sales_report(
        report_date,
        generated,
        rows,
        summary
):

    content = ""


    content += (
        "=" * 150
        + "\n"
    )

    content += (
        " " * 55
        +
        "DAILY SALES REPORT\n"
    )

    content += (
        "=" * 150
        + "\n\n"
    )


    content += (
        f"Report Generated : {generated}\n"
    )

    content += (
        f"Report Date      : {report_date}\n\n"
    )


    content += _format_sales_table(rows)


    content += "\n"
    content += "DAILY SALES SUMMARY\n"
    content += "\n"


    content += (
        f"Total Products Sold       : {summary['products']}\n"
    )

    content += (
        f"Total Quantity Sold       : {summary['quantity']} Units\n"
    )

    content += (
        f"Total Cost of Goods Sold  : M{summary['cost']:.2f}\n"
    )

    content += (
        f"Gross Sales               : M{summary['gross_sales']:.2f}\n"
    )

    content += (
        f"Total Discount             : M{summary['discount']:.2f}\n"
    )

    content += (
        f"Net Sales                  : M{summary['net_sales']:.2f}\n"
    )

    content += (
        f"Profit/Loss                : M{summary['profit']:.2f}\n"
    )


    content += "\n"
    content += "=" * 150
    content += "\n"
    content += "Generated by POS System\n"
    content += "=" * 150


    filename = (
        f"daily_sales_{report_date}.txt"
    )


    return _save_text_file(
        filename,
        content
    )

# ==========================================================
# MONTHLY SALES REPORT EXPORT
# ==========================================================

def save_monthly_sales_report(
        month,
        generated,
        rows,
        summary
):

    content = ""


    content += (
        "=" * 150
        + "\n"
    )


    content += (
        " " * 55
        +
        "MONTHLY SALES REPORT\n"
    )


    content += (
        "=" * 150
        + "\n\n"
    )


    content += (
        f"Report Generated : {generated}\n"
    )


    content += (
        f"Period           : {month}\n\n"
    )


    content += _format_sales_table(rows)



    content += "\n"
    content += "MONTHLY SALES SUMMARY\n"
    content += "\n"



    content += (
        f"Total Products Sold       : {summary['products']}\n"
    )


    content += (
        f"Total Quantity Sold       : {summary['quantity']} Units\n"
    )


    content += (
        f"Total Cost of Goods Sold  : M{summary['cost']:.2f}\n"
    )


    content += (
        f"Gross Sales               : M{summary['gross_sales']:.2f}\n"
    )


    content += (
        f"Total Discount             : M{summary['discount']:.2f}\n"
    )


    content += (
        f"Net Sales                  : M{summary['net_sales']:.2f}\n"
    )


    content += (
        f"Profit/Loss                : M{summary['profit']:.2f}\n"
    )



    content += "\n"
    content += "=" * 150
    content += "\n"
    content += "Generated by POS System\n"
    content += "=" * 150



    filename = (
        f"monthly_sales_{month}.txt"
    )


    return _save_text_file(
        filename,
        content
    )



# ==========================================================
# DAILY STOCK BOOK EXPORT
# ==========================================================

def save_daily_stock_report(
        report_date,
        generated,
        rows
):

    content = ""


    content += (
        "=" * 70
        + "\n"
    )


    content += (
        " " * 22
        +
        "DAILY STOCK BOOK\n"
    )


    content += (
        "=" * 70
        + "\n\n"
    )


    content += (
        f"Report Generated : {generated}\n"
    )


    content += (
        f"Report Date      : {report_date}\n\n"
    )


    content += _format_stock_table(rows)



    content += "\n"
    content += "=" * 70
    content += "\n"
    content += "Generated by POS System\n"
    content += "=" * 70



    filename = (
        f"daily_stock_{report_date}.txt"
    )


    return _save_text_file(
        filename,
        content
    )



# ==========================================================
# MONTHLY STOCK BOOK EXPORT
# ==========================================================

def save_monthly_stock_report(
        month,
        generated,
        rows
):

    content = ""


    content += (
        "=" * 70
        + "\n"
    )


    content += (
        " " * 20
        +
        "MONTHLY STOCK BOOK\n"
    )


    content += (
        "=" * 70
        + "\n\n"
    )


    content += (
        f"Report Generated : {generated}\n"
    )


    content += (
        f"Period           : {month}\n\n"
    )


    content += _format_stock_table(rows)



    content += "\n"
    content += "=" * 70
    content += "\n"
    content += "Generated by POS System\n"
    content += "=" * 70



    filename = (
        f"monthly_stock_{month}.txt"
    )


    return _save_text_file(
        filename,
        content
    )